Makefile.am
metamath.1

Many Linux distributions want a manual page for every executable. We briefly explain what the program does, how to invoke it, and what the language looks like. It doesn't go into detail about the CLI yet, although that could be added later.
I wrote this for OpenSUSE, but I thought it might be helpful for others as well.

Add manual page for metamath executable

---

Makefile.am

Previously the automake variable `dist_pkgdata_DATA` was set to a list
of non-existing `*.mm` databases. This variable controls which files are
installed to `$(datadir)/metamath` during the make targets `install` and
`dist`, which were failing with an error due to the missing
dependencies.

build: Fix broken `install` and `dist` targets

---

mmwtex.c

The head comment was slightly adjusted to avoid referencing the now-deleted section.

remove obsolete rainbow color models

---

mmdata.c
mmhlpb.c

This is mainly just to flag the two places in the code where Norman Megill's email address is given for technical support.  I'm pretty confident it's just these two.  What I've done about it in each case is just a guess on my part which could quite possibly be improved upon.
Naturally I have run Metamath to test both changes in output.

Email address for technical support

---

metamath.c
mmcmdl.c
mmcmdl.h
mmcmds.c
mmcmds.h
mmdata.c
mmdata.h
mmhlpa.c
mmhlpb.c
mminou.c
mminou.h
mmpars.c
mmpars.h
mmpfas.c
mmpfas.h
mmunif.c
mmunif.h
mmveri.c
mmvstr.c
mmvstr.h
mmwtex.c
mmwtex.h

This is a big commit, it touches essentially every file. There should be no behavioral changes in this commit, it is all comment removal / editing except for a few instances of e.g. removing empty `else { }` branches.
I tried to keep as many comments as possible, but remove anything that represents inline evolution of the code (i.e. a comment that says "section added 2-May-04" or explains why a commented out bit of code is commented out). Large commented out blocks of code are also completely removed in most cases.
Ideally, I would like the code to explain itself without reference to history, just saying what the current design is. For the most part, any comment with a date in it has had the date removed, as well as the author (in the vast majority of cases `nm`, of course). I don't think …

remove code history comments & dead code

---

.gitignore
metamath.c
mminou.c

There was only one use of `ssize_t` and it wasn't needed, so I've just removed it. It seems to give errors at `-std=c99` for some compilers, including mine (`gcc 9.3.0`).

add gitignore, fix c99 warnings

---

CONTRIBUTING.md

Sure enough, within minutes of #42 being merged I found a typo in it. As much as I was tempted to wait and see if anyone else said anything or sent in a fix, I'll just send in the fix myself.
Also, change "Why" to "Why not" which seems to read better and/or be
more clear/accurate. This one is perhaps slightly less obvious but at least to my ears it should be a "why not" given the way the previous sentence is worded.

Fix typo (work->worth) in CONTRIBUTING.md

---

src/mmdata.c
src/mmdata.h
src/mminou.c
src/mminou.h
src/mmpars.c
src/mmpars.h
src/mmpfas.c
src/mmpfas.h
src/mmunif.c
src/mmunif.h
src/mmvstr.c
src/mmvstr.h

The memory management pays a lot of attention to whether a returned `vstring` is to be deallocated by the caller, or it is a temporary value which is automatically deallocated by the next call to `let`. This commit makes it clear which is which by using the return type of the function (where `temp_vstring` is a typedef for `vstring`.)
Similarly, a `vstring` is not actually the same as a C `char *`: a `vstring` can be viewed as a `char *`, but it also has a control block at negative addresses which can be used to reallocate the string. Most functions that take `const vstring` are in fact `const char *` methods, so the type signatures have been changed to reflect this. Similarly, many input arguments can be `const`, which is a C99 thing (which was already in the codebase), so use it more …

add types for temp_(v/nmbr/pntr)String, use const

---

src/mmdata.c
src/mmdata.h
src/mmpars.c
src/mmvstr.c
src/mmvstr.h

* Depends on #37
Fix for the issue described in https://github.com/metamath/metamath-exe/pull/37#discussion_r793080285 . The `makeTempAlloc` functions now take a `vstring` and return a `temp_vstring`, rather than mutating the value in place and effectively changing its type. In all existing situations the result was immediately returned so this results in simpler code anyway.
Note that the `makeTempAlloc(x)` call was previously guarded by a condition `x[0] != 0`, because (canonical) empty strings should not be put on the temp stack. This condition has been moved inside the function, so that it can have a clearer contract.

makeTempAlloc returns self instead of type-changing

---

src/metamath.c
src/mmcmdl.c
src/mmcmds.c
src/mmdata.c
src/mmdata.h
src/mmhlpa.c
src/mmhlpb.c
src/mminou.c
src/mmpars.c
src/mmpfas.c
src/mmunif.c
src/mmveri.c
src/mmvstr.c
src/mmvstr.h
src/mmword.c
src/mmwtex.c

* This commit adds macros `free_vstring`, `free_nmbrString` and `free_pntrString` for the idiom `let(&x, "")`, in order to make clear when this is being used to deallocate memory (as opposed to actually setting the value to the empty string).
* It also adds macros `vstring_def`, `nmbrString_def` and `pntrString_def` for the idiom `vstring x = ""`, because this is the only safe way to construct a new `vstring`. (The macro `vstringdef` already existed; it has been renamed to `vstring_def` for consistency with the others and used throughout.)
* In a few places, the idiom `let(&dummy, "")` was being used for its side effect of clearing temporary variables, for example when `mid()` is being called in a loop which does not otherwise contain a `let`. Instead of this, the function …

add macros for alloc/free of string types

---

build.sh

enrich documentation with information about *.c and *.h files.

bugfix doxygen not scanning source files

---

tests/run_test.sh

The escapes here are in single quotes, meaning that they are left uninterpreted and any interpretation of the escapes is being done by `echo`. I tried `echo -e` but that doesn't work in `bash --posix`, but `printf` seems to work to produce the escape character, which can then be interpolated directly into the other variables.
Also swaps out the "white" character for "bright white", which looks the same on linux but also works on windows.

fix color codes on windows

---

tests/disjoint1.expected
tests/disjoint1.in
tests/disjoint1.mm
tests/disjoint2.expected
tests/disjoint2.in
tests/disjoint2.mm
tests/disjoint3.expected
tests/disjoint3.in
tests/disjoint3.mm

As long as I've been saying "we should make a testsuite" I've been thinking in terms of making sure that all flavors of disjoint variable constraint violations are detected. It is one of the quickest way for a verifier to let invalid proofs slip through, or so has been my thought process (certainly when I'm writing proofs it is one of the most common places where the verifier catches me doing something which actually won't work).
Here's a start. My intended technique was to comment out the distinct variable checker (the lines in mmveri.c from `/***** Check for $d violations *****/` to `/***** (End of $d violation check) *****/`), writing a test, and then uncommenting out enough of the checker to get the test to now behave the same way as an unmodified metamath-exe. Well, I got as far as …

Test disjoint

---

src/mmcmdl.h
src/mmcmds.h
src/mmdata.c
src/mmdata.h
src/mmhlpa.c
src/mmhlpa.h
src/mmhlpb.h
src/mminou.h
src/mmpars.h
src/mmpfas.h
src/mmunif.h
src/mmveri.h
src/mmvstr.h
src/mmword.c
src/mmword.h
src/mmwtex.h

This will conflict with #75 to some extent, but I think it will be helpful for @wlammen to work from a base in which most functions are already (poorly) doxygen'd. In particular, the new doxygen comments should include or incorporate all of the text from the original documentation; there were some cases like `temp_vstring` or the mmvstr.h header where sizable comments were ignored when the doxygen comment was added, resulting in two comments with different syntax and somewhat overlapping contents.

Convert comments to doxygen

---

src/metamath.c
src/mmcmdl.h
src/mmdata.c
src/mmdata.h
src/mminou.c
src/mminou.h
src/mmvstr.c
src/mmvstr.h

fix description of cmdInput; improve that of cmdInput1 (version 1)

doc cmdInput1 and dependent(1)

---

src/mmcmds.c
src/mmcmds.h
src/mmhlpa.c
src/mmhlpb.c

The help functions were previously setting a flag g_printHelp
for each block of help commands to print based on the string input from
the user to the help command. The H() function was then internally
checking that g_printHelp flag to determine whether to print
its argument, or do nothing.
It's clearer to have the help-printing functions check the input string,
and then just print the appropriate block then and there. This allows
for the removal of the g_printHelp global flag altogether, and makes the
underlying logic easier to understand.

Remove g_printHelp flag

---

tests/nuniq-gram.expected
tests/nuniq-gram.in
tests/nuniq-gram.mm

So I'll confess that I've written metamath proofs for a long time without really digging into syntax theorems so I'm not really the person to comment on what this means.
But I saw that @digama0 posted this example to the mailing list and it looked like the kind of thing we want in our testsuite.
Feel free to suggest a better comment, or other ways this could be different.

Add example of a non-unique grammar from the mailing list.

---

src/mmcmdl.c
src/mmpars.c

Valgrind found both of these.  In the mmcmdl.c case, tmpStr can point to the allocated memory in the else branch of the if, as well as the then branch, so move free_vstring after the if.  In the mmpars.c case, there was no free_vstring invocation at all.

Plug 2 vstring leaks

---

src/mmwtex.c

After yesterday's valgrind find, I thought it might be interesting to build with `-fsanitize=address`.  Things went well until I decided to run `verify markup */file_skip/top_date_skip`, which resulted in this:
```
Checking latexdef, htmldef, althtmldef...
=================================================================
==25325==ERROR: AddressSanitizer: global-buffer-overflow on address 0x000000566c01 at pc 0x000000501d07 bp 0x7ffea13e1d80 sp 0x7ffea13e1d78
READ of size 1 at 0x000000566c01 thread T0
#0 0x501d06 in readTexDefs /home/jamesjer/src/forked/github/metamath-exe/src/mmwtex.c:482
#1 0x44105e in verifyMarkup /home/jamesjer/src/forked/github/metamath-exe/src/mmcmds.c:5110
#2 0x41f817 in command /home/jamesjer/src/forked/github/metamath-exe/src/metamath.c:6424
#3 0x4025f8 in main …
```

Fix double quote processing in readTexDefs

---

src/mmwtex.c

With metamath built with `-fsanitize=address`, running `verify markup */file_skip/top_date_skip` triggers this error:
```
Checking bibliographic references...
=================================================================
==29102==ERROR: AddressSanitizer: strcpy-param-overlap: memory ranges [0x6180002cf480,0x6180002cf48b) and [0x6180002cf480, 0x6180002cf48b) overlap
#0 0x7fe09ac25fff in __interceptor_strcpy.part.0 (/lib64/libasan.so.8+0x61fff)
#1 0x4dacea in let /home/jamesjer/src/forked/github/metamath-exe/src/mmvstr.c:207
#2 0x505bcb in writeBibliography /home/jamesjer/src/forked/github/metamath-exe/src/mmwtex.c:5376
#3 0x44140d in verifyMarkup /home/jamesjer/src/forked/github/metamath-exe/src/mmcmds.c:5327
#4 0x41f817 in command …
```

Eliminate self-strcpy in writeBibliography

---

.gitignore
build.sh
src/Makefile.am
src/metamath.c
src/mmfatl.c
src/mmfatl.h
src/mmtest.c
src/mmtest.h

The layer printing a final fatal error message must not rely on the memory heap, as it can be exhausted, or even corrupt.  Instead it uses a buffer allocated right at program start for this sole purpose.  It needs this buffer, because it is intended to add simple parsing features to the fatal error message handler.
2 macros control the details of this buffer:
- BUFFERSIZE the capacity of the buffer.  The terminating NUL character must be covered
- ELLIPSIS a string indicating truncation to the user should the parsing overflow the buffer.
This PR allocates a buffer according to the macro settings.  Although C initializes all global variables, we do not rely on this, but assume the buffer might be overwritten in a corrupt environment, and we need to initialize it again.  So far this …

fatal error handling metamath:3

---

.gitignore
src/mmcmdl.c
src/mmdata.c
src/mmfatl.c
src/mminou.c
src/mmtest.h
src/mmvstr.c
src/mmword.c

Adding stream semantics to the buffer.
The parsing algorithm will scan through the format string and continuously add pieces of text to the output buffer.  It will use appendText() to perform this.  This function is meant to copy chunks of text from a source verbatim to the buffer.  It will stop only at a terminating NUL, a placeholder character %, or when the buffer overflows.  The source could either be the format string itself, or a parameter substituting a %s.  Both cases differ slightly:  In case of a parameter the % is just an ordinary character.  Which semantics to select is given by an argument TextType submitted to appendText.

fatal error handling part 4

---

src/mmfatl.c

@digama0 ready to review and merge.  This PR adds a function handleSubstitution that later will be invoked when the parser encounters a % character during his scan of the format string.  The purpose of this function is to check the placeholder type, fetch a parameter from a va_arg list and write the parameter to the output buffer, so that it appears to be inserted.  Afterwards the scan pointer is updated to point behind the placeholder.  There are a couple of irregular situations that are also handled: a % not followed by a recognized type character, overflowing output buffer, and a NULL pointer as a parameter to a string placeholder.

fatal error handling, part 5

---

src/mmfatl.c
src/mmfatl.h

MMFATL_MAX_MSG_SIZE is an externally visible constant.  That it is internally related to a fixed size buffer is an implementation detail, that is now hidden from the name.

fatal error code, part 7

---

src/mmfatl.c
src/mmfatl.h

This is the design and implementation of an interface to mmfatl.  The code in mmfatl is ONLY accessed through this interface.  This allows for independent development on both sides: mmfatl and the rest of Metamath.  As usual, regression tests validate the correctness of the implementation.
Each commit is constrained to a single idea, so a review may visit each commit individually for easiest verification.
Using this interface for error reporting is a final step later done in a dedicated separate PR.
* getFatalErrorPlaceholderToken
* fatalErrorInit is part of the interface
* fatalErrorPush
* fatalErrorPrintAndExit
* fatalErrorExitAt
@digama0 From my point of view the implementation is finished and ready for use in the rest of Metamath

fatal error handling, part 9

---

src/metamath.c
src/mmcmds.c
src/mmhlpa.c
src/mminou.c
src/mmpars.c
src/mmvstr.h
src/mmwtex.c

Remove VAX-related code, which is a task from #17.
(I did global searches on "vax" and "vms", and also on "maci", "mmac", "think" to check no code related to Think C or the old mmmaci.c remained, except possibly in comments.)
Also rewrap some overlong lines.

remove VAX-related code (and rewrap some overlong lines)

---

src/mmfatl.c
src/mmfatl.h

In general it is a good idea that a client queries the capabilities of a service, but in case of the widespread printf format... It is very hypothetical that format strings of error messages are prepared on the assumption something weird could happen to the established grammar service side.  This is likely never be used, get rid of it.
Here I think the general critics apply, but the rest is in good shape from my point of view.  Won't do any more here unsolicited.

dead code elimination in mmfatl

---

src/mmfatl.c
src/mmfatl.h

I tried to make comments after `#endif` more consistent by systematically recalling the identifier that was after the mathching `#if(n)def` directive.  Please @wlammen tell me if this is correct and if I can do that for the other files.
What about removing double blank lines everywhere ? (regex `\n\n\n`)

consistent comment after #endif directives (in files mmfatl.*)

---

refactor.log
src/mmfatl.c
src/mmfatl.h

Mostly: Add the direction of data flow of function parameters to the doxygen \param description.  Occasionally the comments themselves receive minor wording updates.

doxygen [in, out] extension

---

src/mmdata.h
src/mmveri.c

this is a behavior-preserving refactor to move declarations closer to first use, since I was in the area while fixing #107.

cleanup long-lived vars in verifyProof/assignVar

---

src/mmveri.c
tests/issue107.expected
tests/issue107.in
tests/issue107.mm

run unification check even when there are no variables to unify

---

src/mmwtex.c

This pull request does 3 things:
1. Fix checks 1, 9, 13 of  https://github.com/metamath/set.mm/issues/3091 by adding the `accents` package. There was a discussion about long term treatment of these packages, so this is to be considered a temporary solution to not obstruct the flow of https://github.com/metamath/set.mm/pull/3100 according to https://github.com/metamath/set.mm/issues/3091#issuecomment-1474327524 https://github.com/metamath/set.mm/pull/3099#issuecomment-1474323774
2. Fix issue related to relative position between the `amssymb` and `phonetic` packages https://github.com/metamath/set.mm/pull/3090#issuecomment-1465046048
3. Delete `graphicx` package since TeX substitutions with `\rotate` are now replaced with `\riota` in https://github.com/metamath/set.mm/pull/3099

Updated TeX packages

---

src/mmcmds.c
src/mmveri.c

I'm going to try to make a series of PRs like this which moves allocation/initialization of variables to just before first use and deallocation to just after last use, toward #17 "Move variable declarations from top of function to first use".

shrink live ranges:  typeProof, cleanWrkProof

---

src/mmpfas.c

The minimize command used to have an option called `ALLOW_GROWTH` which was replaced in 2019 with `MAY_GROW`, you can find evidence of this change in the `metamath.c` file:
<pre>4-Aug-2019 nm mmhlpb.c, mmcmdl.c, metamath.c - Add /ALLOW_NEW_AXIOMS,
renamed /ALLOW_GROWTH to /MAY_GROW</pre>
There is also a comment made by Norman Megill [here](https://groups.google.com/g/metamath/c/f-L91-1jI24/m/3KJnGa8qCgAJ) where he said:
>The qualifier "/allow_growth" will be changed to "/may_grow" (just a name change to reduce the number of characters you need to type to avoid ambiguity with "/allow_new_axioms").
There are a few lines in `mmpfas.c` that were left behind from this name change, so I updated them.

Allow_growth -> may_grow

---

src/mmword.c

In https://github.com/metamath/metamath-exe/issues/17 I read:
> - [ ]  Use // comments instead of /* (or doc-comments where appropriate)
It doesn't seem a difficult task, so I thought I could give my contribution.
I might continue this if I did a good change.

Line comments instead of block comments

---

src/mmvstr.c

Continuation of #138.
As I was viewing the code, I noticed certain types of comments that I may not be supposed to edit, so I chose to omit them. These comments can be categorized into four groups:
1. Comments with `/*!***/`: They seem to have a special type of formatting, which is consistent with some C files I came across that were not created by Norm. Specifically, I looked at `mmfatl.c` by @wlammen and `mmtest.c` by @digama0, both of which have comments already updated in the `//` form, except for the `/*!***/` ones, so they seem to be intentionally built this way.
2. Comments that have multiple `***`: It appears that they are intended to be noticeable, for example like the header that is present at the beginning of every file: …

Line comments instead of block comments 2

---

src/metamath.c
src/mmcmdl.c
src/mmcmdl.h
tests/issue136.expected
tests/issue136.in

The original implementation concatenated all the arguments with spaces, which is not correct (causes a segfault) when the arguments themselves can have spaces. Here we use a much simpler mechanism, just searching for `/` and then `MY_SWITCH`, taking advantage of the fact that every existing switch is one word.
fixes #136

Simplify and harden `switchPos`

---

src/mmcmds.h
src/mmdata.h
src/mmfatl.h
src/mmhlpa.h
src/mmhlpb.h
src/mminou.h
src/mmpars.h
src/mmpfas.h
src/mmunif.h
src/mmveri.h
src/mmvstr.h
src/mmword.h
src/mmwtex.h

Continuation of https://github.com/metamath/metamath-exe/pull/138.
This PR covers all (editable) h files. Same categories described in https://github.com/metamath/metamath-exe/pull/139 are applied. Comments that start with `/*!` are ignored.

Line comments instead of block comments 4

---

src/mmhlpa.c
src/mmhlpb.c

Continuation of #138 
This PR covers the `mmhlpa.c` and `mmhlpb.c` files, which are easy to handle. Only the header is left out.

Line comments instead of block comments 7

---

src/mmcmdl.c

Continuation of #138 
This PR covers the `mmcmdl.c` file. Only the header and one inline comment are left out.

Line comments instead of block comments 8

---

src/mmunif.c

This PR covers the `mmunif.c` file. Only the header, one inline comment and the `/*E*/` comments are left out.

Line comments instead of block comments 9

---

src/mmpfas.c

This PR covers the `mmpfas.c` file. Only the header, a few inline comments and `/*E*/` comments are left out.

Line comments instead of block comments 10

---

src/mmpars.c

This PR covers the `mmpars.c` file. Only the header, a few inline comments and `/*E*/` comments are left out.

Line comments instead of block comments 13

---

src/metamath.c
src/mmunif.c
src/mmwtex.c

This PR covers the `metamath.c` file. Only the header, doxygen comments, `/*E*/` comments and some inline comments are left out.
With this commit I covered all source files of `metamath.exe`. All comments that I didn't cover are either `/*E*/` comments or they fall in one of the categories of #139. 
I'm available to address some of the described exceptions if preferred (like the header, doc-comments, inline comments...). For example, upon revision the header would be like: 
<pre>// *****************************************************************************
//        Copyright (C) 2020  NORMAN MEGILL
//            License terms:  GNU General Public License
// *****************************************************************************
// 34567890123456 (79-character line to adjust …

Line comments instead of block comments 14

---

src/mmhlpa.c
src/mmwtex.c
tests/.gitignore
tests/underscores.expected
tests/underscores.in
tests/underscores.mm

Almost certainly buggy since I don't know the codebase nor the language. Also, probably inefficient since I copied code from a more complex case than just replacing `__` with `_`. This is more like pseudocode than anything else, actually, but I wanted to get the ball rolling since the need for this feature was emphasized in https://github.com/metamath/set.mm/pull/3389#discussion_r1298845431 by @avekens (i.e., we want to display command names like `MINIMIZE_WITH` and `TRACE_BACK` without triggering italics or subscripts in the generated html).
Help would be appreciated (it may be simpler to start another PR). Maybe from @digama0 or @wlammen or @tirix ?

add handling of double underscores in generated html

---

src/mmwtex.c
tests/underscores.expected
tests/underscores.mm

Fixes an issue noted at https://github.com/metamath/metamath-knife/pull/130#issuecomment-1735228209 . The whole bibtag processing was skipped when there is no bibliography, meaning that `[[` would only get turned into `[` if there is a bibliography present which is not great. Now it just treats this the same as an empty or unreadable bibliography: bib tags are linked anyway but a warning is printed.

undouble `[` even if there is no bibliography

---

src/mminou.c
src/mmwtex.c
tests/.gitignore
tests/issue129.expected
tests/issue129.in
tests/issue129.mm
tests/run_test.sh

This is my attempt to fix issue #129. The solution I proposed in https://github.com/metamath/metamath-exe/issues/129#issuecomment-1404255591 is actually not very practical because latex translations get merged togheter pretty early and this makes it difficult to take advantage of that information. So I changed my mind and implemented @david-a-wheeler proposal instead https://github.com/metamath/metamath-exe/issues/129#issuecomment-1435743413. I took inspiration from an analogous functionality already present for HTML: https://github.com/metamath/metamath-exe/blob/ae35c1b2931be8f9683f8bf66d1d10c9b56db706/src/mminou.c#L549-L588
With this change the generated TeX of my [minimal example](https://github.com/metamath/metamath-exe/issues/129#issuecomment-1765135611) seems to work as intended: …

Attempting to fix the curly brackets bug

---

tests/min_found.expected
tests/min_found.in
tests/min_found.mm
tests/min_not_found.expected
tests/min_not_found.in
tests/min_not_found.mm

fixes #165
This PR contains two tests: the first has a proof that can be automatically minimized, the second one cannot. I designed them to be as similar to each other as possible.  This aims to isolate the issue that causes #165 and therefore provide a (hopefully) sound explanation of the phenomenon. 
Additional evidence is provided by the fact that [my edited version of the minimizer](https://github.com/metamath/set.mm/pull/3619#issuecomment-1801361982) can find the test shortening of `th2` in `min_not_found.mm`, which the regular minimizer cannot detect.
The following comments [[1]](https://github.com/metamath/set.mm/pull/3619#issuecomment-1801829461 ) [[2]](https://github.com/metamath/set.mm/pull/3619#issuecomment-1803191534) have been very helpful to figure out the issue, and the …

Add test cases about minimization
