metamath/metamath-exe

metamath.c
mmcmds.c
mmdata.c
mmdata.h

remove DATE_BELOW_PROOF

---

mmwtex.c
mmwtex.h

It has been enabled since 2004, so I think it is safe to say it is here to stay.

remove RAINBOW_OPTION (make it always true)

---

mmwtex.c
mmwtex.h

It's an "experiment" that has been enabled since 2004. I think it was a success.

remove INDENT_HTML_PROOFS (make it always on)

---

metamath.c

rm all references to mmutil

---

.gitignore
build/build.sh

fix missing directory, improve comments

---

build/build.sh
doc/BUILD.md

Reissued PR after network breakdown caused sync trouble between the GitHub repository and my local copy.
Fixed links.  Extended documentation.

avoid sed if possible

---

src/mmcmdl.c
src/mmcmdl.h

The changes here have been specifically itemized into small changes, most of which have a correctness justification. Reviewers are encouraged to look at the commits one at a time. This is in some sense an experiment in how to present refactoring changes in a way that isn't too overwhelming.

refactor: getFullArg

---

src/mmcmdl.c

Continuation of the mmcmdl.c refactor.

refactor: parseCommandLine

---

tests/big-unifier-bad1.expected
tests/big-unifier-bad1.in
tests/big-unifier-bad1.mm

This is taken from the metamath-tests repository and would
have been in the previous metamath-tests change except
that I didn't yet understand the set scroll continuous
issue then.

Add big-unifier-bad1.mm test

---

src/mmdata.c
src/mmdata.h
src/mminou.c
src/mminou.h
src/mmvstr.c
src/mmvstr.h

describe a stack and some associated data.
Start vstring documentation
Start documentation of error handling
Documentation only, no code change.

temporary pntrString

---

src/mmdata.c
src/mmdata.h
src/mminou.c
src/mminou.h
src/mmvstr.c
src/mmvstr.h

doc print2 (1)

---

src/mminou.h

documentation of printLongLine and dependent functions

printLongLine

---

src/mminou.h

doc printLongLine (2)

---

tests/local-var-bad.expected
tests/local-var-bad.in
tests/local-var-bad.mm
tests/local-var-good.expected
tests/local-var-good.in
tests/local-var-good.mm

This is based on an observation by Glauco on the metamath mailing list
and is taken from the relevant lines of set.mm.

Add test for missing $f

---

src/metamath.c
src/mmcmds.c
src/mmwtex.c

Fix a few minor typos, 3 in user-visible strings, 1 in a comment.

Typo fixes

---

README.TXT
src/Makefile.am
src/mmfatl.c
src/mmfatl.h
src/mmvstr.h

Rebuilding #86 from scratch with the intention to simplify review.

fatal error handling  #1

---

src/mmfatl.c
src/mmfatl.h

Mostly clean up and minor improvements

add checkOverflow, clean up style and test code

---

src/mmfatl.c
src/mmfatl.h

adds a handler for usual text (not a placeholder) in a format string

fatal errors part 8

---

refactor.log
src/mmfatl.h

In the past days I ramped up my knowledge about refactoring again. Refactoring is done in wlammen/metamath-exe, branch wl, which is currently a copy of master. From there I will regularly transfer commits to metamath-exe/master, but I won't wait for any acceptance any more. If PRs get delayed, well, then the tip of my branch will slowly grow into a genuine fork.
Refactoring means you improve the code design and functionality bit by bit. Each commit addresses only one isolated aspect of the software, and the preferred small changes will mostly be such, that the code transition will keep the code semantics intact. This will make review fairly easy.
The basic ideas behind my refactoring are notified in the file refactor.log, that hopefully allow people to grasp the motivation and …

refactor #1 explain the design principles of mmfatl

---

src/metamath.c
src/mmcmds.c
src/mmdata.c
src/mmpars.c
src/mmpfas.c
src/mmunif.c
src/mmvstr.c
src/mmwtex.c
src/mmwtex.h

Hopefully this will fix the OOM issue on the website. These issues were found by running `valgrind` on the executable and doing some typical commands.

fix memory leaks

---

src/mmwtex.c

This is the non-style part of #130.

tex generation: \rm-->\mathrm and \usepackage{...}

---

src/mmwtex.c

Continuation of https://github.com/metamath/metamath-exe/pull/138.
The same categories of https://github.com/metamath/metamath-exe/pull/139 are applied, although I had to rely on my intuition to make some decisions, so there are a few exceptions to rule 3 and 4 in some circumstances.

Line comments instead of block comments 3

---

src/mmveri.c
src/mmwtex.c

Continuation of https://github.com/metamath/metamath-exe/pull/138.
This PR covers the `mmveri.c` file. Same categories described in https://github.com/metamath/metamath-exe/pull/139 are applied.
I also committed the [third suggestion in the previous PR](https://github.com/metamath/metamath-exe/pull/142#discussion_r1214306901) because Github didn't apply it.

Line comments instead of block comments 5

---

src/mmcmds.h
src/mminou.c
src/mmpars.h
src/mmvstr.c
src/mmwtex.c

Continuation of https://github.com/metamath/metamath-exe/pull/138.
This PR covers the `mminou.c` file and applies the decision taken in the discussion https://github.com/metamath/metamath-exe/pull/144#discussion_r1214946709 for my previous commits. Doxygen comments are ignored (rule 1 of https://github.com/metamath/metamath-exe/pull/139). Rule 4 is discontinued. I made some exceptions to rule 2 and 3 because of past suggestions, this will be useful for me to have a better understanding of what comments I should left out in the future.

Line comments instead of block comments 6

---

src/mmdata.c

This PR covers the `mmdata.c` file. The header, doxygen comments and a few inline comments are left out. I also excluded some "highlighted" ones like: 
<pre>/*******************************************************************/
/*********** Number string functions *******************************/
/*******************************************************************/</pre>

Line comments instead of block comments 11

---

src/mmcmds.c

This PR covers the `mmcmds.c` file. Only the header and a few inline comments are left out.

Line comments instead of block comments 12
